language: node_js
install:
  - "npm install mocha -g"
  - "npm install sinon"
  - "npm install chai"
  - "npm install -g codecov"
  - "npm install -g istanbul"
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
notifications:
  email:
    recipients:
      - team@jovo.tech
    on_success: never
    on_failure: always

script:
  - "codecov"