language: node_js
install:
  - "npm install lodash"
  - "npm install mocha"
  - "npm install sinon"
  - "npm install chai"
  - "npm install chai-as-promised"
  - "npm install jovo-cli -g"

node_js:
  - "7"
  - "6"
  - "5"
  - "4"

notifications:
  email:
    recipients:
      - team@jovo.tech
    on_success: never
    on_failure: always

