language: node_js
install:
  - "npm install mocha"
  - "npm install sinon"
  - "npm install chai"

node_js:
  - "7"
  - "6"
  - "5"
  - "4"
notifications:
  email:
    recipients:
      - team@jovo.tech
    on_success: never
    on_failure: always

