language: node_js
install:
  - "npm install"
  - "npm run init"
  - "npm run tsc"
  - "npm run tslint"
  - "npm run test"


node_js:
  - "10"


notifications:
  email:
    recipients:
      - team@jovo.tech
    on_success: never
    on_failure: always

